version: '3.9'
services:
  mongo_db:
    container_name: mongo_docker_test
    image: mongo:latest
    ports: 
      - 27018:27017
  api:
    container_name: api_docker_test
    build: .
    ports:
      - 5000:8080
    environment:
      MONGO_URI: mongodb://mongo_db:27017/coderhouse
